// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_command

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommander creates a new instance of MockCommander. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommander(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommander {
	mock := &MockCommander{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommander is an autogenerated mock type for the Commander type
type MockCommander struct {
	mock.Mock
}

type MockCommander_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommander) EXPECT() *MockCommander_Expecter {
	return &MockCommander_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockCommander
func (_mock *MockCommander) Run(ctx context.Context, head string, parts ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(parts) > 0 {
		tmpRet = _mock.Called(ctx, head, parts)
	} else {
		tmpRet = _mock.Called(ctx, head)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, head, parts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, head, parts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, head, parts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommander_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCommander_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - head string
//   - parts ...string
func (_e *MockCommander_Expecter) Run(ctx interface{}, head interface{}, parts ...interface{}) *MockCommander_Run_Call {
	return &MockCommander_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, head}, parts...)...)}
}

func (_c *MockCommander_Run_Call) Run(run func(ctx context.Context, head string, parts ...string)) *MockCommander_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommander_Run_Call) Return(output []byte, err error) *MockCommander_Run_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockCommander_Run_Call) RunAndReturn(run func(ctx context.Context, head string, parts ...string) ([]byte, error)) *MockCommander_Run_Call {
	_c.Call.Return(run)
	return _c
}
